# Generated by Django 5.0.6 on 2025-01-17 10:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0078_alter_analyticlog_analytic_log_type_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="userusergroup",
            name="idx_user_group_id",
        ),
        migrations.AddIndex(
            model_name="geocustomzone",
            index=models.Index(
                fields=["geozone_ptr"], name="core_geocus_geozone_236823_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userusergroup",
            index=models.Index(fields=["user", "user_group"], name="idx_user_group"),
        ),
    ]
