# Generated by Django 5.0.6 on 2025-01-21 10:28

from django.db import migrations, models

from core.models.detection_data import DetectionData


def update_detection_control_status(apps, schema_editor):
    DetectionData.objects.filter(
        detection_control_status="SIGNALED_COLLECTIVITY"
    ).update(detection_control_status="NOT_CONTROLLED")
    DetectionData.objects.filter(detection_control_status="SIGNALED_COMMUNE").update(
        detection_control_status="NOT_CONTROLLED"
    )


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0079_remove_userusergroup_idx_user_group_id_and_more"),
    ]

    operations = [
        migrations.RunPython(update_detection_control_status),
        migrations.AlterModelOptions(
            name="geozone",
            options={"base_manager_name": "objects"},
        ),
        migrations.RemoveIndex(
            model_name="userusergroup",
            name="idx_user_group",
        ),
        migrations.AlterField(
            model_name="detectiondata",
            name="detection_control_status",
            field=models.CharField(
                choices=[
                    ("NOT_CONTROLLED", "NOT_CONTROLLED"),
                    ("CONTROLLED_FIELD", "CONTROLLED_FIELD"),
                    ("PRIOR_LETTER_SENT", "PRIOR_LETTER_SENT"),
                    ("OFFICIAL_REPORT_DRAWN_UP", "OFFICIAL_REPORT_DRAWN_UP"),
                    ("OBSERVARTION_REPORT_REDACTED", "OBSERVARTION_REPORT_REDACTED"),
                    ("VERBALIZED", "VERBALIZED"),
                    ("REHABILITATED", "REHABILITATED"),
                ],
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="historicaldetectiondata",
            name="detection_control_status",
            field=models.CharField(
                choices=[
                    ("NOT_CONTROLLED", "NOT_CONTROLLED"),
                    ("CONTROLLED_FIELD", "CONTROLLED_FIELD"),
                    ("PRIOR_LETTER_SENT", "PRIOR_LETTER_SENT"),
                    ("OFFICIAL_REPORT_DRAWN_UP", "OFFICIAL_REPORT_DRAWN_UP"),
                    ("OBSERVARTION_REPORT_REDACTED", "OBSERVARTION_REPORT_REDACTED"),
                    ("VERBALIZED", "VERBALIZED"),
                    ("REHABILITATED", "REHABILITATED"),
                ],
                max_length=255,
            ),
        ),
        migrations.AddIndex(
            model_name="userusergroup",
            index=models.Index(
                fields=["user_id", "user_group_id"], name="idx_user_group_id"
            ),
        ),
    ]
