# Generated by Django 5.0.6 on 2025-01-21 10:33

from django.db import migrations, models

from core.models.detection_data import DetectionData


def update_detection_control_status(apps, schema_editor):
    DetectionData.objects.filter(detection_control_status="VERBALIZED").update(
        detection_control_status="OFFICIAL_REPORT_DRAWN_UP"
    )


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0080_alter_geozone_options_and_more"),
    ]

    operations = [
        migrations.RunPython(update_detection_control_status),
        migrations.AlterField(
            model_name="detectiondata",
            name="detection_control_status",
            field=models.CharField(
                choices=[
                    ("NOT_CONTROLLED", "NOT_CONTROLLED"),
                    ("CONTROLLED_FIELD", "CONTROLLED_FIELD"),
                    ("PRIOR_LETTER_SENT", "PRIOR_LETTER_SENT"),
                    ("OFFICIAL_REPORT_DRAWN_UP", "OFFICIAL_REPORT_DRAWN_UP"),
                    ("OBSERVARTION_REPORT_REDACTED", "OBSERVARTION_REPORT_REDACTED"),
                    ("REHABILITATED", "REHABILITATED"),
                ],
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="historicaldetectiondata",
            name="detection_control_status",
            field=models.CharField(
                choices=[
                    ("NOT_CONTROLLED", "NOT_CONTROLLED"),
                    ("CONTROLLED_FIELD", "CONTROLLED_FIELD"),
                    ("PRIOR_LETTER_SENT", "PRIOR_LETTER_SENT"),
                    ("OFFICIAL_REPORT_DRAWN_UP", "OFFICIAL_REPORT_DRAWN_UP"),
                    ("OBSERVARTION_REPORT_REDACTED", "OBSERVARTION_REPORT_REDACTED"),
                    ("REHABILITATED", "REHABILITATED"),
                ],
                max_length=255,
            ),
        ),
    ]
