# Generated by Django 5.0.6 on 2025-01-21 10:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0081_alter_detectiondata_detection_control_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="detectiondata",
            name="detection_control_status",
            field=models.CharField(
                choices=[
                    ("NOT_CONTROLLED", "NOT_CONTROLLED"),
                    ("CONTROLLED_FIELD", "CONTROLLED_FIELD"),
                    ("PRIOR_LETTER_SENT", "PRIOR_LETTER_SENT"),
                    ("OFFICIAL_REPORT_DRAWN_UP", "OFFICIAL_REPORT_DRAWN_UP"),
                    ("OBSERVARTION_REPORT_REDACTED", "OBSERVARTION_REPORT_REDACTED"),
                    ("ADMINISTRATIVE_CONSTRAINT", "ADMINISTRATIVE_CONSTRAINT"),
                    ("REHABILITATED", "REHABILITATED"),
                ],
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="historicaldetectiondata",
            name="detection_control_status",
            field=models.CharField(
                choices=[
                    ("NOT_CONTROLLED", "NOT_CONTROLLED"),
                    ("CONTROLLED_FIELD", "CONTROLLED_FIELD"),
                    ("PRIOR_LETTER_SENT", "PRIOR_LETTER_SENT"),
                    ("OFFICIAL_REPORT_DRAWN_UP", "OFFICIAL_REPORT_DRAWN_UP"),
                    ("OBSERVARTION_REPORT_REDACTED", "OBSERVARTION_REPORT_REDACTED"),
                    ("ADMINISTRATIVE_CONSTRAINT", "ADMINISTRATIVE_CONSTRAINT"),
                    ("REHABILITATED", "REHABILITATED"),
                ],
                max_length=255,
            ),
        ),
    ]
