# Generated by Django 5.0.6 on 2025-01-23 09:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0082_alter_detectiondata_detection_control_status_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="detectiondata",
            name="core_detect_detecti_e3c056_idx",
        ),
        migrations.AddIndex(
            model_name="detection",
            index=models.Index(
                fields=["detection_object", "detection_data", "tile_set", "score"],
                name="core_detect_detecti_59b471_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="detectiondata",
            index=models.Index(
                fields=["detection_prescription_status"],
                name="core_detect_detecti_df0c9b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="detectiondata",
            index=models.Index(
                fields=[
                    "detection_validation_status",
                    "detection_control_status",
                    "detection_prescription_status",
                ],
                name="core_detect_detecti_981643_idx",
            ),
        ),
    ]
