# Generated by Django 5.0.6 on 2025-02-27 15:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0083_remove_detectiondata_core_detect_detecti_e3c056_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="geocustomzone",
            name="geo_zones",
            field=models.ManyToManyField(
                related_name="geo_custom_zones", to="core.geozone"
            ),
        ),
        migrations.AlterField(
            model_name="detection",
            name="detection_source",
            field=models.CharField(
                choices=[
                    ("INTERFACE_DRAWN", "INTERFACE_DRAWN"),
                    ("INTERFACE_FORCED_VISIBLE", "INTERFACE_FORCED_VISIBLE"),
                    ("ANALYSIS", "ANALYSIS"),
                ],
                default="INTERFACE_DRAWN",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="historicaldetection",
            name="detection_source",
            field=models.CharField(
                choices=[
                    ("INTERFACE_DRAWN", "INTERFACE_DRAWN"),
                    ("INTERFACE_FORCED_VISIBLE", "INTERFACE_FORCED_VISIBLE"),
                    ("ANALYSIS", "ANALYSIS"),
                ],
                default="INTERFACE_DRAWN",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="objecttypecategoryobjecttype",
            name="object_type_category_object_type_status",
            field=models.CharField(
                choices=[
                    ("VISIBLE", "VISIBLE"),
                    ("OTHER_CATEGORY", "OTHER_CATEGORY"),
                    ("HIDDEN", "HIDDEN"),
                ],
                max_length=255,
            ),
        ),
    ]
