# Generated by Django 5.0.6 on 2025-02-28 09:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0084_geocustomzone_geo_zones_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="GeoCustomZoneCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("color", models.CharField(max_length=255, unique=True)),
                ("name", models.CharField(max_length=255, null=True)),
                ("name_normalized", models.CharField(max_length=255, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RemoveIndex(
            model_name="geocustomzone",
            name="core_geocus_geozone_236823_idx",
        ),
        migrations.AlterField(
            model_name="geozone",
            name="name",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="geozone",
            name="name_normalized",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
