# Generated by Django 5.0.6 on 2025-02-28 10:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0085_geocustomzonecategory_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="geocustomzonecategory",
            name="name_normalized",
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
