# Generated by Django 5.0.6 on 2025-02-28 10:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0086_alter_geocustomzonecategory_name_normalized"),
    ]

    operations = [
        migrations.AlterField(
            model_name="geocustomzonecategory",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="geocustomzonecategory",
            name="name_normalized",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
