# Generated by Django 5.0.6 on 2025-02-28 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0087_alter_geocustomzonecategory_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="geocustomzone",
            name="geo_custom_zone_category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="geo_custom_zones",
                to="core.geocustomzonecategory",
            ),
        ),
    ]
