# Generated by Django 5.0.6 on 2025-02-28 14:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0088_geocustomzone_geo_custom_zone_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="geocustomzone",
            name="color",
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
