# Generated by Django 5.0.6 on 2025-02-28 14:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0089_alter_geocustomzone_color"),
    ]

    operations = [
        migrations.AlterField(
            model_name="geozone",
            name="name",
            field=models.CharField(default="test", max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="geozone",
            name="name_normalized",
            field=models.CharField(default="test", max_length=255),
            preserve_default=False,
        ),
    ]
