# Generated by Django 5.0.6 on 2025-02-28 15:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0090_alter_geozone_name_alter_geozone_name_normalized"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="geocustomzone",
            index=models.Index(
                fields=["geozone_ptr"], name="core_geocus_geozone_236823_idx"
            ),
        ),
    ]
