# Generated by Django 5.0.6 on 2025-03-05 10:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0091_geocustomzone_core_geocus_geozone_236823_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="detectiondata",
            name="official_report_date",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="historicaldetectiondata",
            name="official_report_date",
            field=models.DateField(null=True),
        ),
    ]
