# Generated by Django 5.0.6 on 2025-03-24 08:58

from django.db import migrations

VIEW_SQL = """
CREATE OR REPLACE VIEW public.geocustomzone_active_enriched
AS SELECT core_geozone.id,
    core_geozone.name,
    core_geocustomzone.color,
    core_geocustomzone.geo_custom_zone_status,
    core_geocustomzone.geo_custom_zone_type,
    core_geozone.geometry
   FROM core_geocustomzone
     JOIN core_geozone ON core_geozone.id = core_geocustomzone.geozone_ptr_id
  WHERE core_geocustomzone.geo_custom_zone_status::text = 'ACTIVE'::text;

CREATE OR REPLACE VIEW public.tileset_enriched
AS SELECT core_tileset.id,
    core_tileset.name,
    st_union(core_geozone.geometry) AS geometry
   FROM core_tileset
     LEFT JOIN core_tileset_geo_zones ON core_tileset_geo_zones.tileset_id = core_tileset.id
     LEFT JOIN core_geozone ON core_geozone.id = core_tileset_geo_zones.geozone_id
  GROUP BY core_tileset.id, core_tileset.name;

CREATE OR REPLACE VIEW public.users
AS SELECT DISTINCT ON (core_user.id) 
    core_user.id,
    core_user.uuid,
    core_user.email,
    core_user.user_role,
    core_user.last_position,
    core_usergroup.id AS group_id,
    core_usergroup.name AS group_name,
    core_userusergroup.user_group_rights AS group_rights,
    core_user.date_joined
   FROM core_user
     LEFT JOIN core_userusergroup ON core_userusergroup.user_id = core_user.id
     LEFT JOIN core_usergroup ON core_usergroup.id = core_userusergroup.user_group_id;
"""

DROP_VIEW_SQL = """
DROP VIEW IF EXISTS public.geocustomzone_active_enriched;
DROP VIEW IF EXISTS public.tileset_enriched;
DROP VIEW IF EXISTS public.users;
"""


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0092_detectiondata_official_report_date_and_more"),
    ]

    operations = [
        migrations.RunSQL(VIEW_SQL, reverse_sql=DROP_VIEW_SQL),
    ]
