# Generated by Django 5.0.6 on 2025-04-15 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0094_alter_user_managers_detectionobject_tile_sets_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="detectionobject",
            name="commune",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="detection_objects",
                to="core.geocommune",
            ),
        ),
        migrations.AddField(
            model_name="historicaldetectionobject",
            name="commune",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="core.geocommune",
            ),
        ),
        migrations.AlterField(
            model_name="detectionobject",
            name="parcel",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="detection_objects",
                to="core.parcel",
            ),
        ),
        migrations.AlterField(
            model_name="parcel",
            name="num_parcel",
            field=models.IntegerField(),
        ),
    ]
