# Generated by Django 5.0.6 on 2025-05-21 13:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0096_alter_geozone_geo_zone_type_geosubcustomzone"),
    ]

    operations = [
        migrations.AddField(
            model_name="detectionobject",
            name="geo_sub_custom_zones",
            field=models.ManyToManyField(
                related_name="detection_objects", to="core.geosubcustomzone"
            ),
        ),
    ]
