# Generated by Django 5.0.6 on 2025-05-22 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0097_detectionobject_geo_sub_custom_zones"),
    ]

    operations = [
        migrations.CreateModel(
            name="GeoEpci",
            fields=[
                (
                    "geozone_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.geozone",
                    ),
                ),
                ("siren_code", models.CharField(max_length=255, unique=True)),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="epcis",
                        to="core.geodepartment",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("core.geozone",),
        ),
    ]
