# Generated by Django 5.0.6 on 2025-05-22 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0098_geoepci"),
    ]

    operations = [
        migrations.AddField(
            model_name="geocommune",
            name="epci",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="communes",
                to="core.geoepci",
            ),
        ),
        migrations.AlterField(
            model_name="geozone",
            name="geo_zone_type",
            field=models.CharField(
                choices=[
                    ("COMMUNE", "COMMUNE"),
                    ("EPCI", "EPCI"),
                    ("DEPARTMENT", "DEPARTMENT"),
                    ("REGION", "REGION"),
                    ("CUSTOM", "CUSTOM"),
                    ("SUB_CUSTOM", "SUB_CUSTOM"),
                ],
                editable=False,
                max_length=255,
            ),
        ),
    ]
