# Generated by Django 5.0.6 on 2025-06-16 06:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0100_geocustomzone_name_short_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="analyticlog",
            name="analytic_log_type",
            field=models.CharField(
                choices=[
                    ("REPORT_DOWNLOAD", "REPORT_DOWNLOAD"),
                    ("PRIOR_LETTER_DOWNLOAD", "PRIOR_LETTER_DOWNLOAD"),
                    ("USER_ACCESS", "USER_ACCESS"),
                ],
                max_length=255,
            ),
        ),
    ]
