# Generated by Django 5.0.6 on 2025-06-18 08:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0102_commandrun"),
    ]

    operations = [
        migrations.AddField(
            model_name="commandrun",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
