# Generated by Django 5.0.6 on 2025-07-11 09:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0103_commandrun_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commandrun",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "PENDING"),
                    ("RUNNING", "RUNNING"),
                    ("SUCCESS", "SUCCESS"),
                    ("ERROR", "ERROR"),
                    ("CANCELED", "CANCELED"),
                ],
                default="PENDING",
                max_length=255,
            ),
        ),
        migrations.AddIndex(
            model_name="parcel",
            index=models.Index(
                fields=["commune"], name="core_parcel_commune_de3824_idx"
            ),
        ),
    ]
