# Generated by Django 5.0.6 on 2025-07-15 12:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0105_detection_core_detect_detecti_36201c_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="parcel",
            name="geo_custom_zones",
            field=models.ManyToManyField(
                related_name="parcels", to="core.geocustomzone"
            ),
        ),
        migrations.AddField(
            model_name="parcel",
            name="geo_sub_custom_zones",
            field=models.ManyToManyField(
                related_name="parcels", to="core.geosubcustomzone"
            ),
        ),
    ]
