# Generated by Django 5.0.6 on 2025-09-18 09:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0106_parcel_geo_custom_zones_parcel_geo_sub_custom_zones"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicaluser",
            name="user_role",
            field=models.CharField(
                choices=[
                    ("SUPER_ADMIN", "SUPER_ADMIN"),
                    ("ADMIN", "ADMIN"),
                    ("REGULAR", "REGULAR"),
                    ("DEACTIVATED", "DEACTIVATED"),
                ],
                default="REGULAR",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="user_role",
            field=models.CharField(
                choices=[
                    ("SUPER_ADMIN", "SUPER_ADMIN"),
                    ("ADMIN", "ADMIN"),
                    ("REGULAR", "REGULAR"),
                    ("DEACTIVATED", "DEACTIVATED"),
                ],
                default="REGULAR",
                max_length=255,
            ),
        ),
    ]
