# Generated by Django 5.0.6 on 2025-09-22 08:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0107_alter_historicaluser_user_role_alter_user_user_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaluser",
            name="is_staff",
            field=models.BooleanField(default=False, verbose_name="staff status"),
        ),
        migrations.AddField(
            model_name="user",
            name="is_staff",
            field=models.BooleanField(default=False, verbose_name="staff status"),
        ),
    ]
