# Generated by Django 5.0.6 on 2025-10-09 09:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0108_historicaluser_is_staff_user_is_staff"),
    ]

    operations = [
        migrations.AddField(
            model_name="detectiondata",
            name="detection_validation_status_change_reason",
            field=models.CharField(
                choices=[("SITADEL", "SITADEL")], max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="detectiondata",
            name="legitimate_date",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="historicaldetectiondata",
            name="detection_validation_status_change_reason",
            field=models.CharField(
                choices=[("SITADEL", "SITADEL")], max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="historicaldetectiondata",
            name="legitimate_date",
            field=models.DateField(null=True),
        ),
    ]
