# Generated by Django 5.0.6 on 2025-10-16 09:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "core",
            "0109_detectiondata_detection_validation_status_change_reason_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="detectiondata",
            name="legitimate_id",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="historicaldetectiondata",
            name="legitimate_id",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
