# Generated by Django 5.0.6 on 2025-10-16 15:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0111_remove_detectiondata_legitimate_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="detectionauthorization",
            name="authorization_id",
            field=models.CharField(null=True),
        ),
    ]
