# Generated by Django 5.0.6 on 2025-10-23 14:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0112_alter_detectionauthorization_authorization_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tileset",
            name="date",
            field=models.DateTimeField(),
        ),
    ]
