# Generated by Django 5.0.6 on 2025-12-19 14:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0114_email_alter_historicaluser_date_joined_and_more"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                CREATE OR REPLACE FUNCTION calculate_surface_m2(geom geometry)
                RETURNS double precision
                LANGUAGE plpgsql
                IMMUTABLE
                AS $$
                BEGIN
                    -- For metropolitan France, use Lambert-93 (EPSG:2154)
                    -- For other territories, you might need different projections
                    RETURN ST_Area(ST_Transform(geom, 2154));
                END;
$$;
            """,
            reverse_sql="DROP FUNCTION IF EXISTS calculate_surface_m2(geometry);",
        ),
    ]
