# Generated by Django 5.0.6 on 2026-04-13 12:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0115_add_calculate_surface_function"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserActionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("route", models.CharField(max_length=255)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("CREATE", "CREATE"),
                            ("UPDATE", "UPDATE"),
                            ("PARTIAL_UPDATE", "PARTIAL_UPDATE"),
                            ("DESTROY", "DESTROY"),
                            ("CUSTOM", "CUSTOM"),
                        ],
                        max_length=255,
                    ),
                ),
                ("data", models.JSONField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="user_action_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["created_at"], name="core_userac_created_6c28e2_idx"
                    ),
                    models.Index(
                        fields=["user"], name="core_userac_user_id_fbcbd1_idx"
                    ),
                    models.Index(
                        fields=["action"], name="core_userac_action_0a27b8_idx"
                    ),
                    models.Index(
                        fields=["user", "created_at"],
                        name="core_userac_user_id_079621_idx",
                    ),
                ],
            },
        ),
    ]
