# Generated by Django 5.0.6 on 2026-06-12

from django.contrib.postgres.operations import AddIndexConcurrently
from django.db import migrations, models


class Migration(migrations.Migration):
    # CREATE INDEX CONCURRENTLY cannot run inside a transaction block: this
    # migration is non-atomic so the multi-million-row detection tables stay
    # writable while the indexes build during deploy. If a concurrent build is
    # interrupted it can leave an INVALID index behind — drop it manually
    # before re-running the migration.
    atomic = False

    dependencies = [
        ("core", "0120_add_jugement_detection_control_status"),
    ]

    operations = [
        # The three AlterField operations only sync model/migration drift that
        # predates this change (choices/max_length metadata): they emit no
        # table rewrite.
        migrations.AlterField(
            model_name="detectionauthorization",
            name="authorization_id",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="detectiondata",
            name="detection_validation_status_change_reason",
            field=models.CharField(
                choices=[
                    ("SITADEL", "SITADEL"),
                    ("EXTERNAL_API", "EXTERNAL_API"),
                    ("IMPORT_FROM_LUCCA", "IMPORT_FROM_LUCCA"),
                ],
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicaldetectiondata",
            name="detection_validation_status_change_reason",
            field=models.CharField(
                choices=[
                    ("SITADEL", "SITADEL"),
                    ("EXTERNAL_API", "EXTERNAL_API"),
                    ("IMPORT_FROM_LUCCA", "IMPORT_FROM_LUCCA"),
                ],
                max_length=255,
                null=True,
            ),
        ),
        # Covering indexes for the deployed-data full-dataset aggregates (see
        # DeployedDataService): they let the per-commune GROUP BY queries run as
        # index-only scans instead of multi-GB heap scans.
        AddIndexConcurrently(
            model_name="detectiondata",
            index=models.Index(
                condition=models.Q(
                    ("detection_validation_status_change_reason__isnull", False)
                ),
                fields=["detection_validation_status_change_reason", "id"],
                name="detectiondata_reason_idx",
            ),
        ),
        AddIndexConcurrently(
            model_name="detectionobject",
            index=models.Index(
                condition=models.Q(("commune__isnull", False)),
                fields=["id", "commune"],
                name="detobj_id_commune_idx",
            ),
        ),
    ]
