# Generated by Django 5.0.14 on 2026-06-17 08:28

from django.contrib.postgres.operations import AddIndexConcurrently
from django.db import migrations, models


class Migration(migrations.Migration):
    # CREATE INDEX CONCURRENTLY cannot run inside a transaction block: this
    # migration is non-atomic so the ~9.6M-row detection-object table stays
    # writable while the index builds during deploy (same pattern as 0121). If a
    # concurrent build is interrupted it can leave an INVALID index behind — drop
    # it manually before re-running the migration.
    atomic = False

    dependencies = [
        ("core", "0121_deployed_data_aggregate_indexes"),
    ]

    operations = [
        # commune-LEADING covering index so the per-department deployed-data detail
        # can SEEK objects by `commune_id IN (...)` (and serve the detection-join
        # object side index-only) instead of full-scanning the table. See
        # DeployedDataService._compute_department_detail.
        AddIndexConcurrently(
            model_name="detectionobject",
            index=models.Index(
                condition=models.Q(("commune__isnull", False)),
                fields=["commune", "id"],
                name="detobj_commune_id_idx",
            ),
        ),
    ]
