# Generated by Django 5.0.14 on 2026-06-26 12:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0127_commandrun_origin_and_timing"),
    ]

    operations = [
        migrations.AddField(
            model_name="geocustomzone",
            name="import_layer_name",
            field=models.CharField(editable=False, max_length=255, null=True),
        ),
    ]
