# Generated by Django 5.0.14 on 2026-08-06 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0129_detection_batch_import_id_unique"),
    ]

    operations = [
        migrations.AlterField(
            model_name="geocommune",
            name="epci",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="communes",
                to="core.geoepci",
            ),
        ),
    ]
