# Generated by Django 5.0.14 on 2026-08-18 15:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0130_geocommune_epci_set_null"),
    ]

    operations = [
        migrations.AddField(
            model_name="geocustomzone",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
