# Generated by Django 5.0.14 on 2026-09-09 12:28

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0133_usergroup_feature_flags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="email",
            name="email_type",
            field=models.CharField(
                choices=[
                    ("CONTACT_US", "CONTACT_US"),
                    ("MFA_LOGIN_LINK", "MFA_LOGIN_LINK"),
                ],
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="usergroup",
            name="feature_flags",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("STATS", "Statistiques"),
                        ("REQUIRE_2FA", "Double authentification obligatoire"),
                    ],
                    max_length=255,
                ),
                blank=True,
                default=list,
                size=None,
            ),
        ),
    ]
