# Generated by Django 5.0.14 on 2026-09-25 08:58

import django.db.models.deletion
import django.db.models.expressions
import django.db.models.lookups
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0133_usergroup_feature_flags"),
    ]

    operations = [
        migrations.CreateModel(
            name="PathValidationProgress",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="path_validation_progress",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("completed_at", models.DateTimeField(null=True)),
                ("checked_items", models.PositiveIntegerField(default=0)),
                ("item_count", models.SmallIntegerField()),
            ],
        ),
        migrations.AddConstraint(
            model_name="pathvalidationprogress",
            constraint=models.CheckConstraint(
                check=models.Q(("item_count__gte", 1), ("item_count__lte", 31)),
                name="path_validation_progress_item_count_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="pathvalidationprogress",
            constraint=models.CheckConstraint(
                check=models.Q(
                    django.db.models.lookups.Exact(
                        django.db.models.expressions.CombinedExpression(
                            models.F("checked_items"), ">>", models.F("item_count")
                        ),
                        0,
                    )
                ),
                name="path_validation_progress_checked_items_in_range",
            ),
        ),
        # Free space on each page keeps every toggle a HOT update, with no PK index write.
        migrations.RunSQL(
            "ALTER TABLE core_pathvalidationprogress SET (fillfactor = 90);",
            reverse_sql="ALTER TABLE core_pathvalidationprogress RESET (fillfactor);",
        ),
    ]
