# Generated by Django 5.0.14 on 2026-10-06 08:24

import django.contrib.postgres.fields
from django.db import migrations, models

# Statistics are open to every user now. Left in the database, the flag would fail the
# user group form validation on the group's next save.
DROP_STATS = """
    UPDATE core_usergroup
    SET feature_flags = array_remove(feature_flags, 'STATS')
    WHERE 'STATS' = ANY(feature_flags)
"""


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0134_pathvalidationprogress"),
    ]

    operations = [
        migrations.RunSQL(DROP_STATS, migrations.RunSQL.noop),
        migrations.AlterField(
            model_name="usergroup",
            name="feature_flags",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(choices=[], max_length=255),
                blank=True,
                default=list,
                size=None,
            ),
        ),
    ]
