# Generated by Django 5.0.14 on 2026-09-16 07:13

import django.contrib.postgres.fields
from django.db import migrations, models

# Le flag disparaît des choices : laissé en base, il ferait échouer la validation du
# formulaire de groupe à la première modification.
DROP_REQUIRE_2FA = """
    UPDATE core_usergroup
    SET feature_flags = array_remove(feature_flags, 'REQUIRE_2FA')
    WHERE 'REQUIRE_2FA' = ANY(feature_flags)
"""


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0134_alter_email_email_type_alter_usergroup_feature_flags"),
    ]

    operations = [
        migrations.RunSQL(DROP_REQUIRE_2FA, migrations.RunSQL.noop),
        migrations.AlterField(
            model_name="email",
            name="email_type",
            field=models.CharField(
                choices=[("CONTACT_US", "CONTACT_US")], max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="usergroup",
            name="feature_flags",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[("STATS", "Statistiques")], max_length=255
                ),
                blank=True,
                default=list,
                size=None,
            ),
        ),
    ]
