# Generated by Django 5.0.14 on 2026-10-08 15:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0136_merge_20261008_1200"),
    ]

    operations = [
        migrations.AddField(
            model_name="tileset",
            name="shown_in_layers_panel",
            field=models.BooleanField(default=True),
        ),
    ]
